### ISSUE TITLE
Proposal: Add a new flag to generate another type String()

### ISSUE THREAD

**Issue by xiekeyi98** [cloudwego/thriftgo#119]
**Is your feature request related to a problem? Please describe.**

It is inconvenience when I print logs with String().
%#v it is not readable enough.

**Describe the solution you'd like**

I suppose we could add a new flag to indicate another String() function.
Such as
-generate_json_string() to indicate thriftgo generate the string() function with "json.MarshalString()"

**Comment by HeyJavaBean** [comment]
I agree.
