### ISSUE TITLE
Missing context.Context in the generated code

### ISSUE THREAD

**Issue by justlorain** [cloudwego/thriftgo#145]
**Describe the bug**

生成的 go 文件中许多方法缺少 context.Context 作为第一个参数

**To Reproduce**

1. test.thrift
```thrift
namespace go test

enum EntryType {
    Normal = 0,
    Config = 1,
}

struct Entry {
    1: optional EntryType type,
    2: optional i64 term,
    3: optional i64 index,
    4: optional binary command,
}
```
2. `thriftgo -g go test.thrift`

**Screenshots**

![image](https://github.com/cloudwego/thriftgo/assets/87760338/e2bcfb60-a399-4be1-965a-94f3eeaab5be)

**Environment:**

thriftgo 0.3.2
go 1.21.0

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/kitex/issues/908
