### ISSUE TITLE
Seems dump tool don't support annotations on Functions

### ISSUE THREAD

**Issue by 2011aad** [cloudwego/thriftgo#170]
**Describe the bug**

When using dump tool to translate an ast into thrift files, annotations of functions will disappear in dumped file.
`func DumpIDL(ast *parser.Thrift) (string, error)`

**To Reproduce**

1. in `tool/trimmer/test_cases/sample1.thrift`, append `(api.get="/hello") ` at the end of line 127
2. Run `TestDumpSingle` in `tool/trimmer/dump/dump_test.go`
3. the output of `DumpIDL` function do not have `(api.get="/hello") ` 

**Expected behavior**

Expect `(api.get="/hello") ` appears in the output of `DumpIDL` function.

**Screenshots**
![image](https://github.com/cloudwego/thriftgo/assets/9875980/39c2ee4e-0cbd-4e3b-a54b-cc2946b8b958)

**Suggestion**
It seems that the `FunctionTemplate` missing the annotation part. Add the following line of code seems work fine.

`const FunctionTemplate = `
{{define "Function"}}
{{- if .ReservedComments}}{{"    "}}{{- ReplaceQuotes .ReservedComments -}}{{"\n"}}{{end -}}
{{"    "}}{{if .Oneway}}oneway {{end}}{{template "Type" .FunctionType}} {{.Name}}(
{{- range $index, $element := .Arguments}}
{{- if $index}}, {{end -}}{{- template "SingleLineField" .}}
{{- end}})
{{- if .Throws}}
{{- "throws" }} (
{{- range $index, $element := .Throws}}
{{- if $index}},{{end -}}{{- template "SingleLineField" .}}
{{- end}})
{{- end}}
_***{{- template "Annotations" .Annotations -}}***_
{{- end -}}
``

**Comment by HeyJavaBean** [comment]
Thanks for feedback.
