### ISSUE TITLE
Add document for plugins?

### ISSUE THREAD

**Issue by niczy** [cloudwego/thriftgo#21]
Can we add document for plugins?

**Comment by lsjbd** [comment]
The package **plugin** has some documents in its comments: https://pkg.go.dev/github.com/cloudwego/thriftgo/plugin. See if it solves your question.

**Comment by choleraehyq** [comment]
@lsjbd Is there any example of the reference implementation of the plugin?

**Comment by lsjbd** [comment]
> @lsjbd Is there any example of the reference implementation of the plugin?

@choleraehyq We will provide some simple examples in the future. By the moment, the kitex command line tool may be the only plugin implementation whose source is public available. It is not so well written, but still an actual example demonstrating how to implement a plugin. See https://github.com/cloudwego/kitex/tree/develop/tool/internal/pkg/pluginmode/thriftgo.
