### ISSUE TITLE
Modify the file header of the generated code

### ISSUE THREAD

**Issue by lhpqaq** [cloudwego/thriftgo#230]
**Is your feature request related to a problem? Please describe.**

Control the file header of the code generated by thriftgo. 

**Describe the solution you'd like**

For example, writing the version number into a .thriftgo file.

**Describe alternatives you've considered**

**Additional context**

https://github.com/cloudwego/hertz/issues/1185

**Comment by lhpqaq** [comment]
@FGYFFFF Thanks~

**Comment by HeyJavaBean** [comment]
Thanks for your suggestion. We've already considered this before, writing the version at each file's header is very important for debug, and in some situation, files under gen_go (or hertz_gen) are combined from multi thriftgo version, so writing version number into a file can not work.

To solve your issus, you can simpily modify some git diff config to ignore the first line.
