### ISSUE TITLE
Generate option `thrift_import_path` leaving unused default Thrift library

### ISSUE THREAD

**Issue by ii64** [cloudwego/thriftgo#34]
Hello, generated code has default thrift library as `thrift0`, leaving it unused.

Generate comand: `thriftgo -o . --gen go:gen_deep_equal=true,frugal_tag=true,thrift_import_path=github.com/apache/thrift/lib/go/thrift/x model.thrift`

![image](https://user-images.githubusercontent.com/26342994/166166767-2adf3d23-1971-4bbb-9939-538d56fc2939.png)

Thanks.

**Comment by lsjbd** [comment]
The PR seems more like a walk around rather than a fix. The issue affects not only the thrift library but all imported libraries.

There are more works needed to be done.
