### ISSUE TITLE
compile error in generated go code with use_type_alias=false and `typedef`-ed struct type

### ISSUE THREAD

**Issue by unnamed42** [cloudwego/thriftgo#79]
**Describe the bug**

As stated in the title.

**To Reproduce**

With thrift file `test.thrift`:

```thrift
namespace go test

struct Req {
    1: required i64 id,
}

typedef Req Req2
```

And thriftgo command

```bash
$ thriftgo --gen go:use_type_alias=false --out test test.thrift
```

Will produce uncompilable code like:

```go
type Req2 Req

func NewReq2() *Req2 {
	return NewReq() // this line fails
}
```

**Expected behavior**

The generated code should compiles well.

**Environment:**

<details>
<code>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOROOT="/usr/local/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5h/hw5wnt8d0q91n8yl5h5p1sdw0000gp/T/go-build20884326=/tmp/go-build -gno-record-gcc-switches -fno-common"
</code>
</details>

**Comment by HeyJavaBean** [comment]
ok，I'll check it later.

**Comment by HeyJavaBean** [comment]
fixed
