### ISSUE TITLE
Please add release for tag 0.2.9

### ISSUE THREAD

**Issue by Rainshaw** [cloudwego/thriftgo#91]
https://github.com/Homebrew/homebrew-core/pull/127198

**Comment by Rainshaw** [comment]
@HeyJavaBean please help, thanks

**Comment by HeyJavaBean** [comment]
We will release a new version and make release log at next middle version (v0.3.0). Before that, you can use 'go install github.com/cloudwego/thriftgo@latest' to install thriftgo.
