### ISSUE TITLE
version field did not get updated for the latest release 0.2.10

### ISSUE THREAD

**Issue by chenrui333** [cloudwego/thriftgo#95]
👋 it looks like the [version field](https://github.com/cloudwego/thriftgo/blob/main/main.go#L29) did not get changed for the latest release.

relates to https://github.com/Homebrew/homebrew-core/pull/128688

**Comment by HeyJavaBean** [comment]
Sorry about that. The version field indeed need to be changed. If you are not in a hurry，we will fix this when we release next version.

**Comment by chenrui333** [comment]
yeah, that works, just raise the issue in here for some awareness. Thanks!
