### ISSUE TITLE
cannot use comment with field in one line

### ISSUE THREAD

**Issue by Rainshaw** [cloudwego/thriftgo#96]
**Describe the bug**

As for now, thriftgo only support head comment for field struct service, but we want to use trailing comment for field. because the heading comment for field will make the line of file grow 2x.

**To Reproduce**
```thrift
namespace go platform
struct PingReq {
    1: string message // filed comment1
}

struct PongResp {
    // field comment2
    1: string message
}

service Platform {
    PongResp Ping(PingReq req)(api.get='/ping')
}
```
use hertz to genCode
```
hz new -idl=idl.thrift
```
**Expected behavior**

PingRep.Message should have a trailing comment.

**Screenshots**

**Kitex version:**

Please provide the version of Kitex you are using.

**Environment:**

The output of `go env`.

**Additional context**

**Comment by HeyJavaBean** [comment]
ok，we will support this later.
